### ISSUE TITLE
error in get_rmax.

### ISSUE THREAD

**Issue by agsreejith** [nespinoza/limb-darkening#4]
Hey Nestor,

I was running your code and is facing error in get_rmax().  It seems fine_r_max is a null vector.

  LDC.append(calc_lds(*iset))
  File "limb-darkening/get_lds.py", line 1055, in calc_lds
    new_r = r/fine_r_max
ValueError: operands could not be broadcast together with shapes (78,) (0,)

Do you have any idea why this would be happening?

Cheers
Sreejith

**Comment by nespinoza** [comment]
Dear Sreejith,

 Could you please provide a working example with which to reproduce the error? Once I have that at hand, I could see what is going on :-). Also, what Python version are you using?

 Best,

Néstor

**Comment by agsreejith** [comment]
Dear Néstor,

I am using python 2.7.6 
The inputs to get_lds was as follows
get_lds( 6000.0,4.5,0.0,-1.0,./inputs/new_pass.txt, FT P100,2895.21364624499,2895.21364624499)
where new_pass is a simple top-hat function with wavelength from 2894 to 5706.

Please let me know if you need additional information 

Cheers
Sreejith

**Comment by agsreejith** [comment]
Dear Néstor,

Any update on the problem?

Cheers
Sreejith
